-- Add email_logs table for tracking sent emails
-- Safe to run across environments.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'email_logs'
  ) THEN
    CREATE TABLE public.email_logs (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at timestamp with time zone DEFAULT now() NOT NULL,
      sent_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
      recipient text NOT NULL,
      subject text NOT NULL,
      status text DEFAULT 'sent' NOT NULL,
      message_id text,
      error_message text
    );

    -- Create index for querying
    CREATE INDEX idx_email_logs_created_at ON public.email_logs(created_at DESC);
    CREATE INDEX idx_email_logs_sent_by ON public.email_logs(sent_by);
    CREATE INDEX idx_email_logs_recipient ON public.email_logs(recipient);

    -- Enable RLS
    ALTER TABLE public.email_logs ENABLE ROW LEVEL SECURITY;

    -- Admins and schedulers can view all
    CREATE POLICY "Admins and schedulers view all emails" ON public.email_logs
      FOR SELECT
      USING (auth.uid() IN (
        SELECT id FROM public.profiles WHERE role_tier IN ('admin', 'scheduler')
      ));

    -- Users can view their own sent emails
    CREATE POLICY "Users view own sent emails" ON public.email_logs
      FOR SELECT
      USING (sent_by = auth.uid());

    RAISE NOTICE 'Created email_logs table';
  END IF;
END
$$;
