-- Populate training_courses with Careskills course names
-- These are the exact course names from the Excel file

INSERT INTO training_courses (name, careskills_name, expiry_months)
VALUES
  ('Lone Working (Careskills)', 'Lone Working (Careskills)', 12),
  ('Mental Health (Careskills)', 'Mental Health (Careskills)', 12),
  ('Person Centred Care (Careskills)', 'Person Centred Care (Careskills)', 12),
  ('First Aid (Careskills)', 'First Aid (Careskills)', 12),
  ('Fire Safety (Careskills)', 'Fire Safety (Careskills)', 12),
  ('Infection Control (Careskills)', 'Infection Control (Careskills)', 12),
  ('The Oliver McGowan Mandatory Training', 'The Oliver McGowan Mandatory Training', 12),
  ('Medication Practice (Careskills)', 'Medication Practice (Careskills)', 12),
  ('Health and Safety (Careskills)', 'Health and Safety (Careskills)', 12),
  ('Safeguarding and Protection of Adults (Careskills)', 'Safeguarding and Protection of Adults (Careskills)', 12),
  ('Self-Harm (Careskills)', 'Self-Harm (Careskills)', 12),
  ('Recording Information (Careskills)', 'Recording Information (Careskills)', 12),
  ('CYP Safeguarding Children and Young People (Careskills)', 'CYP Safeguarding Children and Young People (Careskills)', 12),
  ('Nutrition and Hydration (Careskills)', 'Nutrition and Hydration (Careskills)', 12),
  ('Equality, Diversity, Inclusion (Careskills)', 'Equality, Diversity, Inclusion (Careskills)', 12),
  ('Communication (Careskills)', 'Communication (Careskills)', 12),
  ('GDPR 1 (Careskills)', 'GDPR 1 (Careskills)', 12),
  ('Food Hygiene (Careskills)', 'Food Hygiene (Careskills)', 12),
  ('Diabetes Awareness (Careskills)', 'Diabetes Awareness (Careskills)', 12),
  ('Positive Behaviour Support (Careskills)', 'Positive Behaviour Support (Careskills)', 12),
  ('Personal Care (Careskills)', 'Personal Care (Careskills)', 12),
  ('Care Certificate (Careskills)', 'Care Certificate (Careskills)', 12),
  ('Prevent Extremism and Radicalisation (Careskills)', 'Prevent Extremism and Radicalisation (Careskills)', 12),
  ('Oral Care (Careskills)', 'Oral Care (Careskills)', 12),
  ('Mental Capacity (Careskills)', 'Mental Capacity (Careskills)', 12),
  ('Managing Continence (Careskills)', 'Managing Continence (Careskills)', 12),
  ('Moving and Handling (Careskills)', 'Moving and Handling (Careskills)', 12),
  ('LGBTQ+ Aware for Care (Careskills)', 'LGBTQ+ Aware for Care (Careskills)', 12),
  ('Behaviours that Challenge (Careskills)', 'Behaviours that Challenge (Careskills)', 12),
  ('Epilepsy Awareness (Careskills)', 'Epilepsy Awareness (Careskills)', 12),
  ('Risk Assessment (Careskills)', 'Risk Assessment (Careskills)', 12),
  ('Supervision (Careskills)', 'Supervision (Careskills)', 12),
  ('GDPR 2 (Careskills)', 'GDPR 2 (Careskills)', 12),
  ('Dignity in Care (Careskills)', 'Dignity in Care (Careskills)', 12),
  ('Professional Boundaries (Careskills)', 'Professional Boundaries (Careskills)', 12),
  ('Anxiety (Careskills)', 'Anxiety (Careskills)', 12),
  ('Dysphagia (Careskills)', 'Dysphagia (Careskills)', 12),
  ('Care Certificate Assessor Tutorial (Careskills)', 'Care Certificate Assessor Tutorial (Careskills)', 12),
  ('Cyber Security Awareness (Careskills)', 'Cyber Security Awareness (Careskills)', 12),
  ('Learning Disability (Careskills)', 'Learning Disability (Careskills)', 12),
  ('Autism (Careskills)', 'Autism (Careskills)', 12),
  ('COSHH (Careskills)', 'COSHH (Careskills)', 12),
  ('CYP Introduction to Supporting Children (Careskills)', 'CYP Introduction to Supporting Children (Careskills)', 12),
  ('Infection Control Lite (Careskills)', 'Infection Control Lite (Careskills)', 12),
  ('Induction to Mental Health (Careskills)', 'Induction to Mental Health (Careskills)', 12),
  ('End of Life Care (Careskills)', 'End of Life Care (Careskills)', 12),
  ('Manual Handling of Objects (Careskills)', 'Manual Handling of Objects (Careskills)', 12)
ON CONFLICT (name) DO UPDATE SET
  careskills_name = EXCLUDED.careskills_name;
